sudo: false
before_script:
- curl -LSfs https://japaric.github.io/trust/install.sh | sh -s -- --git cobalt-org/cobalt.rs
  --crate cobalt --force --target x86_64-unknown-linux-gnu
- export PATH="$PATH:~/.cargo/bin"
script:
- cobalt build
deploy:
  provider: pages
  edge:
    branch: v1.8.47
  skip_cleanup: true
  github_token: "$GH_TOKEN"
  local_dir: _site
  target_branch: master
  on:
    branch: source
env:
  global:
  - secure: WpKz9QnUDSpGOPmdr1E0zNLdM1p7AnWLtH9m8dvlkR555qFbCivy/bvAMWVYFpmFzmPeg97BrZh5PeEkYIjUX+2yG5iAEiGLa47AFtqeSnXZdpX4QgUKomP/oZ+ECpySXE0vAf5rXknQhD8LQyOtSHeYH2ZYfgkXmA5ScTFwHIliOs5Rh4NVwP5jy5eu83xAsrdjqd/uAV2ySZWw3cXi1VwkWFmRBIVVx2YHOdmT6ywVteDYFM75Om8apcTu3uuVnJ03sfDHt9dii4k5T80vNL6Cy42uFzLOe8IzA0Flx2OfBC7A0bPT7XYEgYGC7BlloL9V2aXHWRxaCpP7ds1+A8pgFTd6Yz0eGpbx8IAWUibiRmrupzJv/BfSwLy7t7dYWMzq+SP+jYmauiDX+REVDPSGRTke7rdaCkz39OwOycAVae5g8C8njuPyAHLSRRFVxQYTapNAqFAJtpIyCuaU4IGkSUMVdpKXG2Yv6Mg9uL+grLZ7QzVCrzdJMMGaYprHNnMspn1/GVQbImJWLbFPgKxAsP25rSX08mNTM+S7jh3W/GjcgeMgEWSAuQgTihqOadhfcM6kmf2DPjC3WcQJZlbmMEv4fi8ot60xIQNu6ymPQgiZ1TLSw5BeoYwdY/wXEF8DPi94sLAwe/1B2oZU4G77ebp5hP7RpMShcHEonZU=
  - secure: HIHZYwxNuhVtSkFiGH7AaAkax8oJJofX9WN1MKsXZ7Hp2YX6+dvqBoUX63GFOE7eJD3OuvrRA80QW/xOffo0f3LE6oImTvFX+86V8zNZg8UmQKmFwJOsjFsm1lHgpLIcXuQstRh2eBdD3F+Mfku6GHYJeBT660fToXsT3qh5Xi2UvN77HTRdPFyxjRgxZdONPALR307/DfW93VmvzfL+mMgG9Vux0ovYwEun7ArwCuevcI4WRYXsAZYxc6OQsfvpS2QL7jXP79A1IInmDi7FQqh0jSwfZZXDEn2Jyw3KzLzoSFhrXiLAG1+B60G1qsHzcytR36ibb2HcDrOkQxP1JUK1wgD78NZgjBL8dkXXY9WS3v2Rj+Ghb/sH0LlqEUMzrCksWKcP/hRyCZyeZFLpDzHSEOHLp0pX0H0JbkJQOGvf/3fO4ycS+3eN4U4HQwG0Flv0C211xdOHrXubThWIUgK5BEa7+MzWlDQp9R9fyFWZfUZTi5GzJZLazPaitFzQcwFWGhCXOoB5EaOuWZhCCGtZqUi6JzJebR8vNyGVe4AgSPNB/ELquFunHPs5FEpRRCm+xKNHb6kvuSqU120RNRbcePDJNYeMa7fBmByddYQRbYB5zipPfRJzrlR2BSBLnbjQRcfR4DIfQHO8xd2V7/Pa3/0ii6t7hoRqx07yBEw=
